#!/bin/sh
yum install bzip2
yum install git
yum install tmux
yum install dos2unix
curl https://repo.continuum.io/archive/Anaconda2-4.3.1-Linux-x86_64.sh > Anaconda2-4.3.1-Linux-x86_64.sh
bash Anaconda2-4.3.1-Linux-x86_64.sh
mkdir /var/myfiles
cd /var/myfiles
conda install gensim
git clone https://github.com/philipperemy/financial-news-dataset.git
git clone https://github.com/philipperemy/Reuters-full-data-set.git
git clone https://github.com/genkamita-gmo/nlp-forex-predict.git
